import "../app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar";
import Title from "@/components/Title";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Movie App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Title title="nextjs13" />
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
