import { Metadata } from "next";

export default function Title({ title }: { title: string }) {
  const metadata: Metadata = {
    title: `${title} | Next Movies`,
    description: "Generated by create next app",
  };
  return (
    <head>
      <title>{title} | Next Movies</title>
    </head>
  );
}
